[package]
name = "minimization"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
libafl = {path = '/home/peiwithhao/repo/LibAFL/libafl/', features = ["std", "derive"] }
libafl_bolts = {path = '/home/peiwithhao/repo/LibAFL/libafl_bolts/'}
clap = {version = "4.5.37", features = ["derive"]}
log = { version = "0.4.22", features = ["release_max_level_info"] }
nix = {version = "0.29.0", features = ["signal"]}
